name: musicplayer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
objectbox:
  output_dir: database

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  smtc_windows:
    git:
      url: https://github.com/erikas-taroza/frb_plugins.git
      ref: main
      path: packages/smtc_windows

  # State Management
  provider: ^6.1.1

  # Audio
  audioplayers: ^6.0.0
  audiotags: ^1.4.5
  audio_video_progress_bar: ^2.0.2
  audio_service_mpris: ^0.2.0
  audio_service: ^0.18.16

  # File Management
  file_picker: ^10.1.2
  file_saver: ^0.2.12
  path_provider: ^2.1.2
  watcher: ^1.1.1

  # Database
  objectbox: ^4.0.1
  objectbox_flutter_libs: any

  # UI
  image: ^4.2.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  bot_toast: ^4.1.3
  after_layout: ^1.1.0
  flutter_miniplayer: ^1.0.1
  duration: ^4.0.3
  mesh_gradient: ^1.3.8

  # System
  bitsdojo_window: ^0.1.6
  desktop_drop: ^0.5.0
  tray_manager: ^0.5.0
  flutter_single_instance: ^1.2.3
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  objectbox_generator: any
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: FluentIcons-Resizable
      fonts:
        - asset: assets/fonts/FluentSystemIcons-Resizable.ttf